"""Visual constants."""

from .assets import resolve_font_path
from .colors import (
    COLOR_AMBER,
    COLOR_AQUA,
    COLOR_BRICK_RED,
    COLOR_CHARCOAL,
    COLOR_CORAL,
    COLOR_DEEP_TEAL,
    COLOR_FOG_GRAY,
    COLOR_NEAR_BLACK,
    COLOR_SLATE_GRAY,
    COLOR_SOFT_WHITE,
)
from .theme import FONT_FAMILY_DEFAULT, FONT_PATH_ROBOTO_REGULAR, FONT_SIZE_STATUS_COMPACT, STATUS_SEPARATOR_SLASH

__all__ = [
    "COLOR_AQUA",
    "COLOR_DEEP_TEAL",
    "COLOR_CORAL",
    "COLOR_BRICK_RED",
    "COLOR_SLATE_GRAY",
    "COLOR_FOG_GRAY",
    "COLOR_CHARCOAL",
    "COLOR_NEAR_BLACK",
    "COLOR_SOFT_WHITE",
    "COLOR_AMBER",
    "FONT_FAMILY_DEFAULT",
    "FONT_PATH_ROBOTO_REGULAR",
    "FONT_SIZE_STATUS_COMPACT",
    "STATUS_SEPARATOR_SLASH",
    "resolve_font_path",
]
